#include <iostream>
#include <fstream>
#include <string>
#include <vector>

using namespace std;

// Class to hold participant details
class Participant {
public:
    string name;
    string email;
    string domain; // e.g., Web Dev, AI, App Dev

    Participant(string n, string e, string d) {
        name = n;
        email = e;
        domain = d;
    }
};

// Function to generate the HTML Frontend
void generateHTML(vector<Participant>& participants) {
    ofstream htmlFile("hackathon_dashboard.html");

    if (!htmlFile) {
        cout << "Error creating HTML file!" << endl;
        return;
    }

    // Writing HTML structure via C++
    htmlFile << "<!DOCTYPE html>" << endl;
    htmlFile << "<html><head><title>Hackathon Registrations</title>" << endl;
    htmlFile << "<style>" << endl;
    htmlFile << "body { font-family: Arial, sans-serif; background-color: #f4f4f4; text-align: center; }" << endl;
    htmlFile << "table { margin: auto; border-collapse: collapse; width: 80%; background: white; box-shadow: 0px 0px 10px gray; }" << endl;
    htmlFile << "th, td { padding: 12px; border: 1px solid #ddd; text-align: center; }" << endl;
    htmlFile << "th { background-color: #007bff; color: white; }" << endl;
    htmlFile << "h1 { color: #333; margin-top: 50px; }" << endl;
    htmlFile << "</style></head><body>" << endl;

    htmlFile << "<h1>ðŸš€ Hackathon Participant Dashboard</h1>" << endl;
    htmlFile << "<table>" << endl;
    htmlFile << "<tr><th>Name</th><th>Email</th><th>Domain</th></tr>" << endl;

    // Loop through vector and add rows to HTML
    for (const auto& p : participants) {
        htmlFile << "<tr>";
        htmlFile << "<td>" << p.name << "</td>";
        htmlFile << "<td>" << p.email << "</td>";
        htmlFile << "<td>" << p.domain << "</td>";
        htmlFile << "</tr>" << endl;
    }

    htmlFile << "</table></body></html>" << endl;
    htmlFile << "<p><i>Generated by C++ Backend System</i></p>" << endl;

    htmlFile.close();
    cout << "\n[SUCCESS] Frontend 'hackathon_dashboard.html' has been updated!" << endl;
}

int main() {
    vector<Participant> participants;
    int choice;
    string name, email, domain;

    cout << "--- Hackathon Management System Backend ---" << endl;

    while (true) {
        cout << "\n1. Register New Participant" << endl;
        cout << "2. Generate/Update HTML Dashboard" << endl;
        cout << "3. Exit" << endl;
        cout << "Enter choice: ";
        cin >> choice;

        if (choice == 1) {
            cout << "Enter Name: ";
            cin.ignore(); // Clear buffer
            getline(cin, name);
            cout << "Enter Email: ";
            cin >> email;
            cout << "Enter Domain (e.g., AI, Web, App): ";
            cin >> domain;
            
            participants.push_back(Participant(name, email, domain));
            cout << "User Registered Successfully!" << endl;
        } 
        else if (choice == 2) {
            if (participants.empty()) {
                cout << "No participants to display! Register someone first." << endl;
            } else {
                generateHTML(participants);
                cout << "Open 'hackathon_dashboard.html' in your browser to see the result." << endl;
            }
        } 
        else if (choice == 3) {
            break;
        } 
        else {
            cout << "Invalid choice. Try again." << endl;
        }
    }
    return 0;
}
